-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.article_stars
(
    user_id bigint NOT NULL,
    article_id bigint NOT NULL,
    CONSTRAINT article_stars_pkey PRIMARY KEY (user_id, article_id)
);

CREATE TABLE IF NOT EXISTS public.articles
(
    id serial NOT NULL,
    user_id bigint,
    title text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    image_url text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT articles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    id bigserial NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    qty integer NOT NULL,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id),
    CONSTRAINT cart_items_cart_id_product_id_key UNIQUE (cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.carts
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT carts_pkey PRIMARY KEY (id),
    CONSTRAINT carts_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id bigserial NOT NULL,
    name citext COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.comment_reactions
(
    id serial NOT NULL,
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    reaction character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT comment_reactions_pkey PRIMARY KEY (id),
    CONSTRAINT comment_reactions_comment_id_user_id_key UNIQUE (comment_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    post_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    parent_comment_id integer,
    likes integer DEFAULT 0,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course_modules
(
    id bigserial NOT NULL,
    course_id integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    "position" integer NOT NULL,
    has_quiz boolean DEFAULT false,
    CONSTRAINT course_modules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    id serial NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    modules jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    completed_course boolean NOT NULL DEFAULT false,
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enrollments
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    enrolled_at timestamp with time zone NOT NULL DEFAULT now(),
    meta jsonb DEFAULT '{}'::jsonb,
    status character varying(32) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    completed_at timestamp without time zone,
    CONSTRAINT enrollments_pkey PRIMARY KEY (id),
    CONSTRAINT uq_user_course UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.follows
(
    follower_id bigint NOT NULL,
    following_id bigint NOT NULL,
    CONSTRAINT follows_pkey PRIMARY KEY (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS public.likes
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT post_likes_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_post_like UNIQUE (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.module_quizzes
(
    id bigserial NOT NULL,
    module_id bigint NOT NULL,
    pass_score integer DEFAULT 70,
    required boolean DEFAULT true,
    CONSTRAINT module_quizzes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    actor_id bigint,
    type character varying(50) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    items jsonb,
    total_cents integer NOT NULL,
    status character varying(32) COLLATE pg_catalog."default" NOT NULL DEFAULT 'created'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    shipping_address jsonb DEFAULT '{}'::jsonb,
    customer_phone text COLLATE pg_catalog."default",
    billing_address jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pending_users
(
    email text COLLATE pg_catalog."default" NOT NULL,
    fullname text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    otp_hash text COLLATE pg_catalog."default" NOT NULL,
    attempts integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    expires_at timestamp without time zone NOT NULL,
    CONSTRAINT pending_users_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.post_images
(
    id serial NOT NULL,
    post_id bigint NOT NULL,
    image_url text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT post_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.post_reactions
(
    id serial NOT NULL,
    post_id integer,
    user_id integer,
    reaction character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT post_reactions_pkey PRIMARY KEY (id),
    CONSTRAINT post_reactions_post_id_user_id_key UNIQUE (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.posts
(
    id serial NOT NULL,
    user_id bigint,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT posts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id bigserial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price_cents integer NOT NULL,
    image_url text COLLATE pg_catalog."default",
    stock integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.quiz_answers
(
    id bigserial NOT NULL,
    question_id bigint NOT NULL,
    answer text COLLATE pg_catalog."default" NOT NULL,
    is_correct boolean DEFAULT false,
    CONSTRAINT quiz_answers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.quiz_questions
(
    id bigserial NOT NULL,
    quiz_id bigint NOT NULL,
    question text COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    points integer DEFAULT 1,
    CONSTRAINT quiz_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    session_id uuid NOT NULL,
    ua_hash text COLLATE pg_catalog."default" NOT NULL,
    fp_hash text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    revoked_at timestamp with time zone,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_quiz_answers
(
    id bigserial NOT NULL,
    attempt_id bigint NOT NULL,
    question_id bigint NOT NULL,
    answer_id bigint NOT NULL,
    CONSTRAINT user_quiz_answers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_quiz_attempts
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    score integer NOT NULL,
    passed boolean DEFAULT false,
    attempted_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_quiz_attempts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    email citext COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    fullname character varying(200) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    is_admin boolean NOT NULL DEFAULT false,
    avatar_url text COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    website text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

COMMENT ON COLUMN public.users.avatar_url
    IS 'URL to user avatar image';

COMMENT ON COLUMN public.users.bio
    IS 'User biography/description';

COMMENT ON COLUMN public.users.website
    IS 'User personal website URL';

ALTER TABLE IF EXISTS public.article_stars
    ADD CONSTRAINT article_stars_article_id_fkey FOREIGN KEY (article_id)
    REFERENCES public.articles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.article_stars
    ADD CONSTRAINT article_stars_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.articles
    ADD CONSTRAINT articles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id)
    REFERENCES public.carts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_cart_items_cart
    ON public.cart_items(cart_id);


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_cart_items_product
    ON public.cart_items(product_id);


ALTER TABLE IF EXISTS public.comment_reactions
    ADD CONSTRAINT comment_reactions_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES public.comments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.comment_reactions
    ADD CONSTRAINT comment_reactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id)
    REFERENCES public.comments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_post_fk FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_comments_post
    ON public.comments(post_id);


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.course_modules
    ADD CONSTRAINT fk_module_course FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enrollments
    ADD CONSTRAINT enrollments_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollments_course
    ON public.enrollments(course_id);


ALTER TABLE IF EXISTS public.follows
    ADD CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.follows
    ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_post_fk FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_post
    ON public.likes(post_id);


ALTER TABLE IF EXISTS public.likes
    ADD CONSTRAINT likes_user_fk FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_likes_user
    ON public.likes(user_id);


ALTER TABLE IF EXISTS public.module_quizzes
    ADD CONSTRAINT fk_quiz_module FOREIGN KEY (module_id)
    REFERENCES public.course_modules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.post_images
    ADD CONSTRAINT post_images_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.post_reactions
    ADD CONSTRAINT post_reactions_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post_reactions
    ADD CONSTRAINT post_reactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_posts_user
    ON public.posts(user_id);


ALTER TABLE IF EXISTS public.product_categories
    ADD CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.quiz_answers
    ADD CONSTRAINT fk_answer_question FOREIGN KEY (question_id)
    REFERENCES public.quiz_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.quiz_questions
    ADD CONSTRAINT fk_question_quiz FOREIGN KEY (quiz_id)
    REFERENCES public.module_quizzes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_quiz_answers
    ADD CONSTRAINT fk_uqa_attempt FOREIGN KEY (attempt_id)
    REFERENCES public.user_quiz_attempts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_quiz_attempts
    ADD CONSTRAINT fk_attempt_quiz FOREIGN KEY (quiz_id)
    REFERENCES public.module_quizzes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_quiz_attempts
    ADD CONSTRAINT fk_attempt_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;